AWSTemplateFormatVersion: "2010-09-09"
Description: Test deployment using CloudFormation

Parameters:
  SubnetID:
    Type: String
    Default: subnet-d4ae59bf

Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: cluster-deployment

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: log-group-deployment

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: test-role
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ECSSecurityGroup
      GroupDescription: Test Security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: task-deployment
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: !Ref ExecutionRole
      ContainerDefinitions:
        - Name: nginx-container
          Image: nginx:1.17.7
          PortMappings:
            - ContainerPort: 80
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: ecs
      RequiresCompatibilities:
        - EC2
        - FARGATE

  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: test-service
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetID
          SecurityGroups:
            - !GetAtt ContainerSecurityGroup.GroupId

  Test-Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "UserID"
          AttributeType: "S"
        -
          AttributeName: "Name"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "UserID"
          KeyType: "HASH"
        -
          AttributeName: "Name"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  Test-Output:
    Description: Table created with this template
    Value: !Ref Test-Table
